### ISSUE TITLE
Opprette hjemside

### ISSUE THREAD

**Issue by Staldvik** [IT2810/it2810-webutvikling-h18-prosjekt-3-10#2]
- [x] Skal vise progresjon over dagens mål (om noen)

- [x] Skal vise førstkommende avtaler (om noen)

- [x] Skal vise todo for dagen/kommende dager

**Comment by Tvedt1** [comment]
- [x] knapp og ikon som linker til profil-side

**Comment by Tvedt1** [comment]
progress circle: 
npm install --save react-native-progress-circle 
import ProgressCircle from 'react-native-progress-circle'
